server:
  port: 8084
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
eureka:
  client:
    service-url:
      defaultZone: [invalid url, do not cite]
    fetch-registry: true
    register-with-eureka: true
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
logging:
  level:
    brave: DEBUG
    zipkin: DEBUG
    io.micrometer.tracing: DEBUG