spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
management:
  tracing:
    sampling:
      probability: 1.0
logging.level.brave: DEBUG
logging.level.zipkin: DEBUG
logging.level.io.micrometer.tracing: DEBUG